name: Provision EC2 with terraform 
on: 
  workflow_dispatch:
jobs:
  provision-ec2:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout repository
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.7
      - name: Terraform Initialize
        run: terraform init
      - name: Terraform Plan
        run: terraform plan -var="ec2_name=my-github-action-ec2" # Pass variable value
        working-directory: ./terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve -var="ec2_name=my-github-action-ec2"
        working-directory: ./terraform
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your desired AWS region
        # env:
        #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #   AWS_DEFAULT_REGION: "us-east-1" # Change to your desired region if needed     
